// Copyright 2024 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ConsoleCreateObjApplyConfiguration represents an declarative configuration of the ConsoleCreateObj type for use
// with apply.
type ConsoleCreateObjApplyConfiguration struct {
	Create *bool `json:"create,omitempty"`
}

// ConsoleCreateObjApplyConfiguration constructs an declarative configuration of the ConsoleCreateObj type for use with
// apply.
func ConsoleCreateObj() *ConsoleCreateObjApplyConfiguration {
	return &ConsoleCreateObjApplyConfiguration{}
}

// WithCreate sets the Create field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Create field is set to the value of the last call.
func (b *ConsoleCreateObjApplyConfiguration) WithCreate(value bool) *ConsoleCreateObjApplyConfiguration {
	b.Create = &value
	return b
}
