// Copyright 2024 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// SetTieredStorageCacheDirOwnershipApplyConfiguration represents an declarative configuration of the SetTieredStorageCacheDirOwnership type for use
// with apply.
type SetTieredStorageCacheDirOwnershipApplyConfiguration struct {
	ExtraVolumeMounts *string                  `json:"extraVolumeMounts,omitempty"`
	Resources         *v1.ResourceRequirements `json:"resources,omitempty"`
}

// SetTieredStorageCacheDirOwnershipApplyConfiguration constructs an declarative configuration of the SetTieredStorageCacheDirOwnership type for use with
// apply.
func SetTieredStorageCacheDirOwnership() *SetTieredStorageCacheDirOwnershipApplyConfiguration {
	return &SetTieredStorageCacheDirOwnershipApplyConfiguration{}
}

// WithExtraVolumeMounts sets the ExtraVolumeMounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtraVolumeMounts field is set to the value of the last call.
func (b *SetTieredStorageCacheDirOwnershipApplyConfiguration) WithExtraVolumeMounts(value string) *SetTieredStorageCacheDirOwnershipApplyConfiguration {
	b.ExtraVolumeMounts = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *SetTieredStorageCacheDirOwnershipApplyConfiguration) WithResources(value v1.ResourceRequirements) *SetTieredStorageCacheDirOwnershipApplyConfiguration {
	b.Resources = &value
	return b
}
