// Copyright 2024 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TopicStatusApplyConfiguration represents an declarative configuration of the TopicStatus type for use
// with apply.
type TopicStatusApplyConfiguration struct {
	ObservedGeneration *int64                            `json:"observedGeneration,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration  `json:"conditions,omitempty"`
	TopicConfiguration []ConfigurationApplyConfiguration `json:"topicConfiguration,omitempty"`
}

// TopicStatusApplyConfiguration constructs an declarative configuration of the TopicStatus type for use with
// apply.
func TopicStatus() *TopicStatusApplyConfiguration {
	return &TopicStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *TopicStatusApplyConfiguration) WithObservedGeneration(value int64) *TopicStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TopicStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TopicStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithTopicConfiguration adds the given value to the TopicConfiguration field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TopicConfiguration field.
func (b *TopicStatusApplyConfiguration) WithTopicConfiguration(values ...*ConfigurationApplyConfiguration) *TopicStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTopicConfiguration")
		}
		b.TopicConfiguration = append(b.TopicConfiguration, *values[i])
	}
	return b
}
